global:
  scrape_interval: 5s

scrape_configs:
  - job_name: freva-gpt-backend
    metrics_path: /metrics
    static_configs:
      - targets: ["freva-gpt-backend:8502"]
  - job_name: code-server
    metrics_path: /metrics
    static_configs:
      - targets: ["code:8051"]